apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
    name: ibm-cert-manager-catalog
    namespace: openshift-marketplace
spec:
    displayName: ibm-cert-manager-4.0.0
    image: icr.io/cpopen/ibm-cert-manager-operator-catalog
    publisher: IBM
    sourceType: grpc
    updateStrategy:
        registryPoll:
            interval: 45m