apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
    name: eem-operator-catalog
    namespace: openshift-marketplace
spec:
    displayName: IBM EEM Catalog
    image: icr.io/cpopen/ibm-eventendpointmanagement-operator-catalog:v11.0.1
    publisher: IBM
    sourceType: grpc
    updateStrategy:
        registryPoll:
            interval: 45m
